import { ToolIcon } from '../../lib/tool-icon-types';

export interface ToolIconPreset {
  name: string;
  icon: string;
  color: string;
}

export const TOOL_ICON_PRESETS: Record<ToolIcon, ToolIconPreset> = {
  [ToolIcon.aarch64]: { name: 'AArch64', icon: 'devicon-aarch64-plain', color: '#567ce5' },
  [ToolIcon.adonisjs]: { name: 'AdonisJS', icon: 'devicon-adonisjs-plain', color: '#8373ff' },
  [ToolIcon.aerospike]: { name: 'Aerospike', icon: 'devicon-aerospike-plain', color: '#ea383b' },
  [ToolIcon.aframe]: { name: 'A-Frame', icon: 'devicon-aframe-plain', color: '#ee295f' },
  [ToolIcon.aftereffects]: { name: 'After Effects', icon: 'devicon-aftereffects-plain', color: '#9a5eed' },
  [ToolIcon.akka]: { name: 'Akka', icon: 'devicon-akka-plain', color: '#15a9ce' },
  [ToolIcon.algolia]: { name: 'Algolia', icon: 'devicon-algolia-original', color: '#4d77ff' },
  [ToolIcon.almalinux]: { name: 'AlmaLinux', icon: 'devicon-almalinux-plain', color: '#ffffff' },
  [ToolIcon.alpinejs]: { name: 'Alpine.js', icon: 'devicon-alpinejs-plain', color: '#6580b2' },
  [ToolIcon.amazonwebservices]: { name: 'Amazon Web Services', icon: 'devicon-amazonwebservices-plain', color: '#f90' },
  [ToolIcon.anaconda]: { name: 'Anaconda', icon: 'devicon-anaconda-plain', color: '#3eb049' },
  [ToolIcon.android]: { name: 'Android', icon: 'devicon-android-plain', color: '#A4C439' },
  [ToolIcon.androidstudio]: { name: 'Android Studio', icon: 'devicon-androidstudio-plain', color: '#4285F4' },
  [ToolIcon.angular]: { name: 'Angular', icon: 'devicon-angular-plain', color: '#FFFFFF' },
  [ToolIcon.angularjs]: { name: 'AngularJS', icon: 'devicon-angularjs-plain', color: '#cc5d51' },
  [ToolIcon.angularmaterial]: { name: 'Angular Material', icon: 'devicon-angularmaterial-plain', color: '#ffa726' },
  [ToolIcon.ansible]: { name: 'Ansible', icon: 'devicon-ansible-plain', color: '#947c65' },
  [ToolIcon.ansys]: { name: 'Ansys', icon: 'devicon-ansys-plain', color: '#828282' },
  [ToolIcon.antdesign]: { name: 'Ant Design', icon: 'devicon-antdesign-plain', color: '#0086da' },
  [ToolIcon.apache]: { name: 'Apache', icon: 'devicon-apache-plain', color: '#df4e5b' },
  [ToolIcon.apacheairflow]: { name: 'Apache Airflow', icon: 'devicon-apacheairflow-plain', color: '#017cee' },
  [ToolIcon.apachekafka]: { name: 'Apache Kafka', icon: 'devicon-apachekafka-plain', color: '#a47480' },
  [ToolIcon.apachespark]: { name: 'Apache Spark', icon: 'devicon-apachespark-plain', color: '#e15919' },
  [ToolIcon.apex]: { name: 'Apex', icon: 'devicon-apex-plain', color: '#0d9dda' },
  [ToolIcon.apl]: { name: 'APL', icon: 'devicon-apl-plain', color: '#24a148' },
  [ToolIcon.apollographql]: { name: 'Apollo GraphQL', icon: 'devicon-apollographql-plain', color: '#3f84d2' },
  [ToolIcon.appcelerator]: { name: 'Appcelerator', icon: 'devicon-appcelerator-plain', color: '#e7465d' },
  [ToolIcon.apple]: { name: 'Apple', icon: 'devicon-apple-plain', color: '#828282' },
  [ToolIcon.appwrite]: { name: 'Appwrite', icon: 'devicon-appwrite-plain', color: '#fd366e' },
  [ToolIcon.archlinux]: { name: 'Arch Linux', icon: 'devicon-archlinux-plain', color: '#1791cf' },
  [ToolIcon.arduino]: { name: 'Arduino', icon: 'devicon-arduino-plain', color: '#00979d' },
  [ToolIcon.argocd]: { name: 'Argo CD', icon: 'devicon-argocd-plain', color: '#ef7b4d' },
  [ToolIcon.artixlinux]: { name: 'Artix Linux', icon: 'devicon-artixlinux-plain', color: '#10a0cc' },
  [ToolIcon.astro]: { name: 'Astro', icon: 'devicon-astro-plain', color: '#ff5d01' },
  [ToolIcon.atom]: { name: 'Atom', icon: 'devicon-atom-plain', color: '#a77583' },
  [ToolIcon.awk]: { name: 'AWK', icon: 'devicon-awk-plain-wordmark', color: '#7c7aef' },
  [ToolIcon.axios]: { name: 'Axios', icon: 'devicon-axios-plain', color: '#8e6ded' },
  [ToolIcon.azure]: { name: 'Azure', icon: 'devicon-azure-plain', color: '#0089D6' },
  [ToolIcon.azuredevops]: { name: 'Azure DevOps', icon: 'devicon-azuredevops-plain', color: '#0081e3' },
  [ToolIcon.azuresqldatabase]: { name: 'Azure SQL Database', icon: 'devicon-azuresqldatabase-plain', color: '#0086ee' },
  [ToolIcon.babel]: { name: 'Babel', icon: 'devicon-babel-plain', color: '#f9dc3e' },
  [ToolIcon.babylonjs]: { name: 'Babylon.js', icon: 'devicon-babylonjs-plain', color: '#c7686c' },
  [ToolIcon.backbonejs]: { name: 'Backbone.js', icon: 'devicon-backbonejs-plain', color: '#0083cb' },
  [ToolIcon.ballerina]: { name: 'Ballerina', icon: 'devicon-ballerina-plain', color: '#46C0BC' },
  [ToolIcon.bamboo]: { name: 'Bamboo', icon: 'devicon-bamboo-plain', color: '#3080f0' },
  [ToolIcon.bash]: { name: 'Bash', icon: 'devicon-bash-plain', color: '#5f87aa' },
  [ToolIcon.bazel]: { name: 'Bazel', icon: 'devicon-bazel-plain', color: '#76D275' },
  [ToolIcon.beats]: { name: 'Beats', icon: 'devicon-beats-plain', color: '#0080db' },
  [ToolIcon.behance]: { name: 'Behance', icon: 'devicon-behance-plain', color: '#0080ff' },
  [ToolIcon.bevyengine]: { name: 'Bevy', icon: 'devicon-bevyengine-plain', color: '#848484' },
  [ToolIcon.biome]: { name: 'Biome', icon: 'devicon-biome-plain', color: '#60a5fa' },
  [ToolIcon.bitbucket]: { name: 'Bitbucket', icon: 'devicon-bitbucket-plain', color: '#3d85cf' },
  [ToolIcon.blazor]: { name: 'Blazor', icon: 'devicon-blazor-plain', color: '#9968d0' },
  [ToolIcon.blender]: { name: 'Blender', icon: 'devicon-blender-original', color: '#DC7B2E' },
  [ToolIcon.bootstrap]: { name: 'Bootstrap', icon: 'devicon-bootstrap-plain', color: '#9968fb' },
  [ToolIcon.bower]: { name: 'Bower', icon: 'devicon-bower-plain', color: '#ef5734' },
  [ToolIcon.browserstack]: { name: 'BrowserStack', icon: 'devicon-browserstack-plain', color: '#107fff' },
  [ToolIcon.bulma]: { name: 'Bulma', icon: 'devicon-bulma-plain', color: '#00d1b2' },
  [ToolIcon.bun]: { name: 'Bun', icon: 'devicon-bun-plain', color: '#FBF0DF' },
  [ToolIcon.c]: { name: 'C', icon: 'devicon-c-plain', color: '#a9bacd' },
  [ToolIcon.cairo]: { name: 'Cairo', icon: 'devicon-cairo-plain', color: '#f39914' },
  [ToolIcon.cakephp]: { name: 'CakePHP', icon: 'devicon-cakephp-plain', color: '#da565c' },
  [ToolIcon.canva]: { name: 'Canva', icon: 'devicon-canva-plain', color: '#00C4CC' },
  [ToolIcon.capacitor]: { name: 'Capacitor', icon: 'devicon-capacitor-plain', color: '#53B9FF' },
  [ToolIcon.carbon]: { name: 'Carbon', icon: 'devicon-carbon-plain', color: '#828282' },
  [ToolIcon.cassandra]: { name: 'Cassandra', icon: 'devicon-cassandra-plain', color: '#1290be' },
  [ToolIcon.centos]: { name: 'CentOS', icon: 'devicon-centos-plain', color: '#d649b5' },
  [ToolIcon.ceylon]: { name: 'Ceylon', icon: 'devicon-ceylon-plain', color: '#AB710A' },
  [ToolIcon.chakraui]: { name: 'Chakra UI', icon: 'devicon-chakraui-plain', color: '#52c8c5' },
  [ToolIcon.chartjs]: { name: 'Chart.js', icon: 'devicon-chartjs-plain', color: '#ff6384' },
  [ToolIcon.chrome]: { name: 'Chrome', icon: 'devicon-chrome-plain', color: '#d15a5a' },
  [ToolIcon.circleci]: { name: 'CircleCI', icon: 'devicon-circleci-plain', color: '#818181' },
  [ToolIcon.clarity]: { name: 'Clarity', icon: 'devicon-clarity-plain', color: '#5b87a8' },
  [ToolIcon.clickhouse]: { name: 'ClickHouse', icon: 'devicon-clickhouse-plain', color: '#f9ff69' },
  [ToolIcon.clion]: { name: 'CLion', icon: 'devicon-clion-plain', color: '#21d789' },
  [ToolIcon.clojure]: { name: 'Clojure', icon: 'devicon-clojure-plain', color: '#5881d8' },
  [ToolIcon.clojurescript]: { name: 'ClojureScript', icon: 'devicon-clojurescript-plain', color: '#96ca4b' },
  [ToolIcon.cloudflare]: { name: 'Cloudflare', icon: 'devicon-cloudflare-plain', color: '#F38020' },
  [ToolIcon.cloudflareworkers]: { name: 'Cloudflare Workers', icon: 'devicon-cloudflareworkers-plain', color: '#ea9344' },
  [ToolIcon.cloudrun]: { name: 'Cloud Run', icon: 'devicon-cloudrun-plain', color: '#4285f4' },
  [ToolIcon.cmake]: { name: 'CMake', icon: 'devicon-cmake-plain', color: '#0f9818' },
  [ToolIcon.cobol]: { name: 'COBOL', icon: 'devicon-cobol-plain', color: '#828282' },
  [ToolIcon.codeac]: { name: 'Codeac', icon: 'devicon-codeac-original', color: '#0081f2' },
  [ToolIcon.codecov]: { name: 'Codecov', icon: 'devicon-codecov-plain', color: '#e43d70' },
  [ToolIcon.codeigniter]: { name: 'CodeIgniter', icon: 'devicon-codeigniter-plain', color: '#ee4323' },
  [ToolIcon.codepen]: { name: 'CodePen', icon: 'devicon-codepen-plain', color: '#828282' },
  [ToolIcon.coffeescript]: { name: 'CoffeeScript', icon: 'devicon-coffeescript-plain', color: '#6583c6' },
  [ToolIcon.composer]: { name: 'Composer', icon: 'devicon-composer-plain', color: '#828282' },
  [ToolIcon.confluence]: { name: 'Confluence', icon: 'devicon-confluence-plain', color: '#2a7ced' },
  [ToolIcon.consul]: { name: 'Consul', icon: 'devicon-consul-plain', color: '#e2457e' },
  [ToolIcon.contao]: { name: 'Contao', icon: 'devicon-contao-original', color: '#f47c00' },
  [ToolIcon.corejs]: { name: 'Core.js', icon: 'devicon-corejs-plain', color: '#828282' },
  [ToolIcon.cosmosdb]: { name: 'Azure Cosmos DB', icon: 'devicon-cosmosdb-plain', color: '#59B3D8' },
  [ToolIcon.couchbase]: { name: 'Couchbase', icon: 'devicon-couchbase-plain', color: '#ed3f43' },
  [ToolIcon.couchdb]: { name: 'CouchDB', icon: 'devicon-couchdb-plain', color: '#e74043' },
  [ToolIcon.cpanel]: { name: 'cPanel', icon: 'devicon-cpanel-plain', color: '#ff6c2c' },
  [ToolIcon.cplusplus]: { name: 'C++', icon: 'devicon-cplusplus-plain', color: '#007ced' },
  [ToolIcon.crystal]: { name: 'Crystal', icon: 'devicon-crystal-plain', color: '#828282' },
  [ToolIcon.csharp]: { name: 'C#', icon: 'devicon-csharp-plain', color: '#b854d1' },
  [ToolIcon.css3]: { name: 'CSS3', icon: 'devicon-css3-plain', color: '#3d8fc6' },
  [ToolIcon.cucumber]: { name: 'Cucumber', icon: 'devicon-cucumber-plain', color: '#00a818' },
  [ToolIcon.cypressio]: { name: 'Cypress', icon: 'devicon-cypressio-plain', color: '#6d7ac2' },
  [ToolIcon.d3js]: { name: 'D3.js', icon: 'devicon-d3js-plain', color: '#f7974e' },
  [ToolIcon.dart]: { name: 'Dart', icon: 'devicon-dart-plain', color: '#00A8E1' },
  [ToolIcon.datadog]: { name: 'Datadog', icon: 'devicon-datadog-plain', color: '#9967d7' },
  [ToolIcon.datagrip]: { name: 'DataGrip', icon: 'devicon-datagrip-plain', color: '#21d789' },
  [ToolIcon.dataspell]: { name: 'DataSpell', icon: 'devicon-dataspell-plain', color: '#087cfa' },
  [ToolIcon.datatables]: { name: 'DataTables', icon: 'devicon-datatables-plain', color: '#ffffff' },
  [ToolIcon.dbeaver]: { name: 'DBeaver', icon: 'devicon-dbeaver-plain', color: '#b07054' },
  [ToolIcon.debian]: { name: 'Debian', icon: 'devicon-debian-plain', color: '#ff054c' },
  [ToolIcon.delphi]: { name: 'Delphi', icon: 'devicon-delphi-plain', color: '#e14e53' },
  [ToolIcon.denojs]: { name: 'Deno', icon: 'devicon-denojs-plain', color: '#828282' },
  [ToolIcon.detaspace]: { name: 'Deta Space', icon: 'devicon-detaspace-line', color: '#f73b95' },
  [ToolIcon.devicon]: { name: 'Devicon', icon: 'devicon-devicon-plain', color: '#60BE86' },
  [ToolIcon.digitalocean]: { name: 'DigitalOcean', icon: 'devicon-digitalocean-plain', color: '#0080FF' },
  [ToolIcon.discloud]: { name: 'Discloud', icon: 'devicon-discloud-plain', color: '#57f287' },
  [ToolIcon.discordjs]: { name: 'Discord.js', icon: 'devicon-discordjs-plain', color: '#7c7cc7' },
  [ToolIcon.django]: { name: 'Django', icon: 'devicon-django-plain', color: '#1d9467' },
  [ToolIcon.djangorest]: { name: 'Django REST', icon: 'devicon-djangorest-plain', color: '#ff0000' },
  [ToolIcon.docker]: { name: 'Docker', icon: 'devicon-docker-plain', color: '#019bc6' },
  [ToolIcon.doctrine]: { name: 'Doctrine', icon: 'devicon-doctrine-plain', color: '#f56d39' },
  [ToolIcon.dotnet]: { name: '.NET', icon: 'devicon-dot-net-plain', color: '#1384c8' },
  [ToolIcon.dotnetcore]: { name: '.NET Core', icon: 'devicon-dotnetcore-plain', color: '#986dcb' },
  [ToolIcon.dovecot]: { name: 'Dovecot', icon: 'devicon-dovecot-plain', color: '#54bbab' },
  [ToolIcon.dreamweaver]: { name: 'Dreamweaver', icon: 'devicon-dreamweaver-plain', color: '#ed03b8' },
  [ToolIcon.dropwizard]: { name: 'Dropwizard', icon: 'devicon-dropwizard-plain', color: '#7c7fcc' },
  [ToolIcon.drupal]: { name: 'Drupal', icon: 'devicon-drupal-plain', color: '#0086d9' },
  [ToolIcon.duckdb]: { name: 'DuckDB', icon: 'devicon-duckdb-plain', color: '#828282' },
  [ToolIcon.dyalog]: { name: 'Dyalog APL', icon: 'devicon-dyalog-plain', color: '#ff6a13' },
  [ToolIcon.dynamodb]: { name: 'DynamoDB', icon: 'devicon-dynamodb-plain', color: '#527fff' },
  [ToolIcon.dynatrace]: { name: 'Dynatrace', icon: 'devicon-dynatrace-plain', color: '#828282' },
  [ToolIcon.eclipse]: { name: 'Eclipse', icon: 'devicon-eclipse-plain', color: '#8676c8' },
  [ToolIcon.ecto]: { name: 'Ecto', icon: 'devicon-ecto-plain', color: '#77bf43' },
  [ToolIcon.elasticsearch]: { name: 'Elasticsearch', icon: 'devicon-elasticsearch-plain', color: '#00bfb3' },
  [ToolIcon.electron]: { name: 'Electron', icon: 'devicon-electron-original', color: '#3b99aa' },
  [ToolIcon.eleventy]: { name: 'Eleventy', icon: 'devicon-eleventy-plain', color: '#828282' },
  [ToolIcon.elixir]: { name: 'Elixir', icon: 'devicon-elixir-plain', color: '#ba54e9' },
  [ToolIcon.elm]: { name: 'Elm', icon: 'devicon-elm-plain', color: '#5186bb' },
  [ToolIcon.emacs]: { name: 'Emacs', icon: 'devicon-emacs-original', color: '#a068ce' },
  [ToolIcon.embeddedc]: { name: 'Embedded C', icon: 'devicon-embeddedc-plain', color: '#818181' },
  [ToolIcon.ember]: { name: 'Ember.js', icon: 'devicon-ember-plain', color: '#E04E39' },
  [ToolIcon.entityframeworkcore]: { name: 'Entity Framework Core', icon: 'devicon-entityframeworkcore-plain', color: '#856be1' },
  [ToolIcon.envoy]: { name: 'Envoy', icon: 'devicon-envoy-plain', color: '#e13eaf' },
  [ToolIcon.erlang]: { name: 'Erlang', icon: 'devicon-erlang-plain', color: '#f81252' },
  [ToolIcon.eslint]: { name: 'ESLint', icon: 'devicon-eslint-plain', color: '#8775dc' },
  [ToolIcon.expo]: { name: 'Expo', icon: 'devicon-expo-plain', color: '#828282' },
  [ToolIcon.express]: { name: 'Express', icon: 'devicon-express-original', color: '#818181' },
  [ToolIcon.facebook]: { name: 'Facebook', icon: 'devicon-facebook-plain', color: '#6280c0' },
  [ToolIcon.fastapi]: { name: 'FastAPI', icon: 'devicon-fastapi-plain', color: '#009688' },
  [ToolIcon.fastify]: { name: 'Fastify', icon: 'devicon-fastify-plain', color: '#828282' },
  [ToolIcon.faunadb]: { name: 'FaunaDB', icon: 'devicon-faunadb-plain', color: '#896fea' },
  [ToolIcon.feathersjs]: { name: 'Feathers.js', icon: 'devicon-feathersjs-original', color: '#808080' },
  [ToolIcon.fedora]: { name: 'Fedora', icon: 'devicon-fedora-plain', color: '#5f81c6' },
  [ToolIcon.fiber]: { name: 'Fiber', icon: 'devicon-fiber-plain', color: '#00acd7' },
  [ToolIcon.figma]: { name: 'Figma', icon: 'devicon-figma-plain', color: '#f24e1e' },
  [ToolIcon.filamentphp]: { name: 'Filament', icon: 'devicon-filamentphp-plain', color: '#828282' },
  [ToolIcon.filezilla]: { name: 'FileZilla', icon: 'devicon-filezilla-plain', color: '#ff090a' },
  [ToolIcon.firebase]: { name: 'Firebase', icon: 'devicon-firebase-plain', color: '#ffa000' },
  [ToolIcon.firebird]: { name: 'Firebird', icon: 'devicon-firebird-plain', color: '#f4790e' },
  [ToolIcon.firefox]: { name: 'Firefox', icon: 'devicon-firefox-plain', color: '#DD732A' },
  [ToolIcon.flask]: { name: 'Flask', icon: 'devicon-flask-plain', color: '#838383' },
  [ToolIcon.flutter]: { name: 'Flutter', icon: 'devicon-flutter-plain', color: '#3FB6D3' },
  [ToolIcon.forgejo]: { name: 'Forgejo', icon: 'devicon-forgejo-plain', color: '#FF5500' },
  [ToolIcon.fortran]: { name: 'Fortran', icon: 'devicon-fortran-original', color: '#996ac8' },
  [ToolIcon.foundation]: { name: 'Foundation', icon: 'devicon-foundation-plain', color: '#008cba' },
  [ToolIcon.framermotion]: { name: 'Framer Motion', icon: 'devicon-framermotion-plain', color: '#828282' },
  [ToolIcon.framework7]: { name: 'Framework7', icon: 'devicon-framework7-plain', color: '#ee350f' },
  [ToolIcon.fsharp]: { name: 'F#', icon: 'devicon-fsharp-plain', color: '#378BBA' },
  [ToolIcon.fusion]: { name: 'Fusion 360', icon: 'devicon-fusion-plain', color: '#FF6A00' },
  [ToolIcon.gardener]: { name: 'Gardener', icon: 'devicon-gardener-plain', color: '#009f76' },
  [ToolIcon.gatling]: { name: 'Gatling', icon: 'devicon-gatling-plain', color: '#f78557' },
  [ToolIcon.gatsby]: { name: 'Gatsby', icon: 'devicon-gatsby-plain', color: '#a16dca' },
  [ToolIcon.gazebo]: { name: 'Gazebo', icon: 'devicon-gazebo-plain', color: '#f58113' },
  [ToolIcon.gcc]: { name: 'GCC', icon: 'devicon-gcc-plain', color: '#ffcfab' },
  [ToolIcon.gentoo]: { name: 'Gentoo', icon: 'devicon-gentoo-plain', color: '#9991d9' },
  [ToolIcon.ghost]: { name: 'Ghost', icon: 'devicon-ghost-original', color: '#828282' },
  [ToolIcon.gimp]: { name: 'GIMP', icon: 'devicon-gimp-plain', color: '#948151' },
  [ToolIcon.git]: { name: 'Git', icon: 'devicon-git-plain', color: '#f34f29' },
  [ToolIcon.gitbook]: { name: 'GitBook', icon: 'devicon-gitbook-plain', color: '#4e80e0' },
  [ToolIcon.github]: { name: 'GitHub', icon: 'devicon-github-plain', color: '#a07373' },
  [ToolIcon.githubactions]: { name: 'GitHub Actions', icon: 'devicon-githubactions-plain', color: '#2088FF' },
  [ToolIcon.githubcodespaces]: { name: 'GitHub Codespaces', icon: 'devicon-githubcodespaces-plain', color: '#6485a6' },
  [ToolIcon.gitkraken]: { name: 'GitKraken', icon: 'devicon-gitkraken-plain', color: '#179287' },
  [ToolIcon.gitlab]: { name: 'GitLab', icon: 'devicon-gitlab-plain', color: '#e44f36' },
  [ToolIcon.gitpod]: { name: 'Gitpod', icon: 'devicon-gitpod-plain', color: '#FFA132' },
  [ToolIcon.gitter]: { name: 'Gitter', icon: 'devicon-gitter-plain', color: '#828282' },
  [ToolIcon.gleam]: { name: 'Gleam', icon: 'devicon-gleam-plain', color: '#ffaff3' },
  [ToolIcon.glitch]: { name: 'Glitch', icon: 'devicon-glitch-plain', color: '#828282' },
  [ToolIcon.go]: { name: 'Go', icon: 'devicon-go-plain', color: '#00acd7' },
  [ToolIcon.godot]: { name: 'Godot', icon: 'devicon-godot-plain', color: '#478cbf' },
  [ToolIcon.goland]: { name: 'GoLand', icon: 'devicon-goland-plain', color: '#087cfa' },
  [ToolIcon.google]: { name: 'Google', icon: 'devicon-google-plain', color: '#6386c1' },
  [ToolIcon.googlecloud]: { name: 'Google Cloud', icon: 'devicon-googlecloud-plain', color: '#557ebf' },
  [ToolIcon.googlecolab]: { name: 'Google Colab', icon: 'devicon-googlecolab-plain', color: '#ffb300' },
  [ToolIcon.gradle]: { name: 'Gradle', icon: 'devicon-gradle-plain', color: '#0692b0' },
  [ToolIcon.grafana]: { name: 'Grafana', icon: 'devicon-grafana-plain', color: '#f7a525' },
  [ToolIcon.grails]: { name: 'Grails', icon: 'devicon-grails-plain', color: '#feb571' },
  [ToolIcon.graphql]: { name: 'GraphQL', icon: 'devicon-graphql-plain', color: '#e434aa' },
  [ToolIcon.groovy]: { name: 'Groovy', icon: 'devicon-groovy-plain', color: '#619cbc' },
  [ToolIcon.grpc]: { name: 'gRPC', icon: 'devicon-grpc-plain', color: '#00b0ad' },
  [ToolIcon.grunt]: { name: 'Grunt', icon: 'devicon-grunt-plain', color: '#fcaa1a' },
  [ToolIcon.gulp]: { name: 'Gulp', icon: 'devicon-gulp-plain', color: '#eb4a4b' },
  [ToolIcon.hadoop]: { name: 'Hadoop', icon: 'devicon-hadoop-plain', color: '#ffff00' },
  [ToolIcon.handlebars]: { name: 'Handlebars', icon: 'devicon-handlebars-plain', color: '#828282' },
  [ToolIcon.harbor]: { name: 'Harbor', icon: 'devicon-harbor-plain', color: '#7d7d7d' },
  [ToolIcon.hardhat]: { name: 'Hardhat', icon: 'devicon-hardhat-plain', color: '#fff100' },
  [ToolIcon.harvester]: { name: 'Harvester', icon: 'devicon-harvester-plain', color: '#00A580' },
  [ToolIcon.haskell]: { name: 'Haskell', icon: 'devicon-haskell-plain', color: '#8571c1' },
  [ToolIcon.haxe]: { name: 'Haxe', icon: 'devicon-haxe-plain', color: '#EA8220' },
  [ToolIcon.helm]: { name: 'Helm', icon: 'devicon-helm-plain', color: '#7077ef' },
  [ToolIcon.heroku]: { name: 'Heroku', icon: 'devicon-heroku-plain', color: '#817bca' },
  [ToolIcon.hibernate]: { name: 'Hibernate', icon: 'devicon-hibernate-plain', color: '#bcae79' },
  [ToolIcon.homebrew]: { name: 'Homebrew', icon: 'devicon-homebrew-plain', color: '#fbb040' },
  [ToolIcon.hoppscotch]: { name: 'Hoppscotch', icon: 'devicon-hoppscotch-plain', color: '#00d196' },
  [ToolIcon.html5]: { name: 'HTML5', icon: 'devicon-html5-plain', color: '#e54d26' },
  [ToolIcon.htmx]: { name: 'htmx', icon: 'devicon-htmx-plain', color: '#808080' },
  [ToolIcon.hugo]: { name: 'Hugo', icon: 'devicon-hugo-plain', color: '#FF4088' },
  [ToolIcon.hyperv]: { name: 'Hyper-V', icon: 'devicon-hyperv-plain', color: '#5773ff' },
  [ToolIcon.ie10]: { name: 'Internet Explorer', icon: 'devicon-ie10-plain', color: '#1EBBEE' },
  [ToolIcon.ifttt]: { name: 'IFTTT', icon: 'devicon-ifttt-plain', color: '#828282' },
  [ToolIcon.illustrator]: { name: 'Illustrator', icon: 'devicon-illustrator-plain', color: '#ff0a0a' },
  [ToolIcon.inertiajs]: { name: 'Inertia.js', icon: 'devicon-inertiajs-plain', color: '#8c71ed' },
  [ToolIcon.influxdb]: { name: 'InfluxDB', icon: 'devicon-influxdb-plain', color: '#6274fb' },
  [ToolIcon.inkscape]: { name: 'Inkscape', icon: 'devicon-inkscape-plain', color: '#828282' },
  [ToolIcon.insomnia]: { name: 'Insomnia', icon: 'devicon-insomnia-plain', color: '#9b68ff' },
  [ToolIcon.intellij]: { name: 'IntelliJ IDEA', icon: 'devicon-intellij-plain', color: '#087cfa' },
  [ToolIcon.ionic]: { name: 'Ionic', icon: 'devicon-ionic-original', color: '#4e8ef7' },
  [ToolIcon.jaegertracing]: { name: 'Jaeger', icon: 'devicon-jaegertracing-plain', color: '#67cfe3' },
  [ToolIcon.jamstack]: { name: 'JAMstack', icon: 'devicon-jamstack-plain', color: '#fb0887' },
  [ToolIcon.jasmine]: { name: 'Jasmine', icon: 'devicon-jasmine-plain', color: '#b562ac' },
  [ToolIcon.java]: { name: 'Java', icon: 'devicon-java-plain', color: '#eb3b3c' },
  [ToolIcon.javascript]: { name: 'JavaScript', icon: 'devicon-javascript-plain', color: '#f0db4f' },
  [ToolIcon.jeet]: { name: 'Jeet', icon: 'devicon-jeet-plain', color: '#FF664A' },
  [ToolIcon.jekyll]: { name: 'Jekyll', icon: 'devicon-jekyll-plain', color: '#828282' },
  [ToolIcon.jenkins]: { name: 'Jenkins', icon: 'devicon-jenkins-plain', color: '#F0D6B7' },
  [ToolIcon.jest]: { name: 'Jest', icon: 'devicon-jest-plain', color: '#be6982' },
  [ToolIcon.jetbrains]: { name: 'JetBrains', icon: 'devicon-jetbrains-plain', color: '#FDCC21' },
  [ToolIcon.jetpackcompose]: { name: 'Jetpack Compose', icon: 'devicon-jetpackcompose-plain', color: '#4285f4' },
  [ToolIcon.jhipster]: { name: 'JHipster', icon: 'devicon-jhipster-plain', color: '#4289c7' },
  [ToolIcon.jira]: { name: 'Jira', icon: 'devicon-jira-plain', color: '#2684ff' },
  [ToolIcon.jiraalign]: { name: 'Jira Align', icon: 'devicon-jiraalign-plain', color: '#2684FF' },
  [ToolIcon.jquery]: { name: 'jQuery', icon: 'devicon-jquery-plain', color: '#0984d9' },
  [ToolIcon.json]: { name: 'JSON', icon: 'devicon-json-plain', color: '#7e7e7e' },
  [ToolIcon.jule]: { name: 'Jule', icon: 'devicon-jule-plain', color: '#5a81ac' },
  [ToolIcon.julia]: { name: 'Julia', icon: 'devicon-julia-plain', color: '#28a745' },
  [ToolIcon.junit]: { name: 'JUnit', icon: 'devicon-junit-plain', color: '#dc514a' },
  [ToolIcon.jupyter]: { name: 'Jupyter', icon: 'devicon-jupyter-plain', color: '#F37726' },
  [ToolIcon.k3os]: { name: 'k3OS', icon: 'devicon-k3os-plain', color: '#fd824e' },
  [ToolIcon.k3s]: { name: 'k3s', icon: 'devicon-k3s-plain', color: '#ffc519' },
  [ToolIcon.k6]: { name: 'k6', icon: 'devicon-k6-plain', color: '#7D64FF' },
  [ToolIcon.kaggle]: { name: 'Kaggle', icon: 'devicon-kaggle-plain', color: '#20BEFF' },
  [ToolIcon.kaldi]: { name: 'Kaldi', icon: 'devicon-kaldi-plain', color: '#a3743a' },
  [ToolIcon.kalilinux]: { name: 'Kali Linux', icon: 'devicon-kalilinux-plain', color: '#2777ff' },
  [ToolIcon.karatelabs]: { name: 'Karate', icon: 'devicon-karatelabs-plain', color: '#828282' },
  [ToolIcon.karma]: { name: 'Karma', icon: 'devicon-karma-plain', color: '#56c5a8' },
  [ToolIcon.kdeneon]: { name: 'KDE Neon', icon: 'devicon-kdeneon-plain', color: '#2689b3' },
  [ToolIcon.keras]: { name: 'Keras', icon: 'devicon-keras-plain', color: '#fe0000' },
  [ToolIcon.kibana]: { name: 'Kibana', icon: 'devicon-kibana-plain', color: '#F04E98' },
  [ToolIcon.knexjs]: { name: 'Knex.js', icon: 'devicon-knexjs-plain', color: '#e16426' },
  [ToolIcon.knockout]: { name: 'Knockout.js', icon: 'devicon-knockout-plain-wordmark', color: '#eb442e' },
  [ToolIcon.kotlin]: { name: 'Kotlin', icon: 'devicon-kotlin-plain', color: '#d522ee' },
  [ToolIcon.krakenjs]: { name: 'Kraken.js', icon: 'devicon-krakenjs-plain', color: '#008bd1' },
  [ToolIcon.ktor]: { name: 'Ktor', icon: 'devicon-ktor-plain', color: '#fc801d' },
  [ToolIcon.kubeflow]: { name: 'Kubeflow', icon: 'devicon-kubeflow-plain', color: '#72a1e5' },
  [ToolIcon.kubernetes]: { name: 'Kubernetes', icon: 'devicon-kubernetes-plain', color: '#4d7fe8' },
  [ToolIcon.labview]: { name: 'LabVIEW', icon: 'devicon-labview-plain', color: '#fed500' },
  [ToolIcon.laminas]: { name: 'Laminas', icon: 'devicon-laminas-plain', color: '#0285ce' },
  [ToolIcon.laravel]: { name: 'Laravel', icon: 'devicon-laravel-plain', color: '#f0513f' },
  [ToolIcon.laraveljetstream]: { name: 'Laravel Jetstream', icon: 'devicon-laraveljetstream-plain', color: '#6875f5' },
  [ToolIcon.latex]: { name: 'LaTeX', icon: 'devicon-latex-plain', color: '#828282' },
  [ToolIcon.leetcode]: { name: 'LeetCode', icon: 'devicon-leetcode-plain', color: '#ffa116' },
  [ToolIcon.less]: { name: 'Less', icon: 'devicon-less-plain-wordmark', color: '#5080c5' },
  [ToolIcon.libgdx]: { name: 'libGDX', icon: 'devicon-libgdx-plain', color: '#e74a45' },
  [ToolIcon.linkedin]: { name: 'LinkedIn', icon: 'devicon-linkedin-plain', color: '#008ad1' },
  [ToolIcon.linux]: { name: 'Linux', icon: 'devicon-linux-plain', color: '#828282' },
  [ToolIcon.linuxmint]: { name: 'Linux Mint', icon: 'devicon-linuxmint-plain', color: '#69b53f' },
  [ToolIcon.liquibase]: { name: 'Liquibase', icon: 'devicon-liquibase-plain', color: '#FF3C00' },
  [ToolIcon.livewire]: { name: 'Livewire', icon: 'devicon-livewire-plain', color: '#FB70A9' },
  [ToolIcon.llvm]: { name: 'LLVM', icon: 'devicon-llvm-plain', color: '#5A90B6' },
  [ToolIcon.lodash]: { name: 'Lodash', icon: 'devicon-lodash-plain', color: '#828282' },
  [ToolIcon.logstash]: { name: 'Logstash', icon: 'devicon-logstash-plain', color: '#fec514' },
  [ToolIcon.love2d]: { name: 'LÖVE', icon: 'devicon-love2d-plain', color: '#fff' },
  [ToolIcon.lua]: { name: 'Lua', icon: 'devicon-lua-plain', color: '#7676ff' },
  [ToolIcon.lumen]: { name: 'Lumen', icon: 'devicon-lumen-plain', color: '#e54537' },
  [ToolIcon.magento]: { name: 'Magento', icon: 'devicon-magento-plain', color: '#f26322' },
  [ToolIcon.mapbox]: { name: 'Mapbox', icon: 'devicon-mapbox-plain', color: '#828282' },
  [ToolIcon.mariadb]: { name: 'MariaDB', icon: 'devicon-mariadb-plain', color: '#0093bf' },
  [ToolIcon.markdown]: { name: 'Markdown', icon: 'devicon-markdown-plain', color: '#828282' },
  [ToolIcon.materializecss]: { name: 'Materialize CSS', icon: 'devicon-materializecss-plain', color: '#EB7077' },
  [ToolIcon.materialui]: { name: 'Material UI', icon: 'devicon-materialui-plain', color: '#1FA6CA' },
  [ToolIcon.matlab]: { name: 'MATLAB', icon: 'devicon-matlab-plain', color: '#6dd0c7' },
  [ToolIcon.matplotlib]: { name: 'Matplotlib', icon: 'devicon-matplotlib-plain', color: '#1c8ccd' },
  [ToolIcon.mattermost]: { name: 'Mattermost', icon: 'devicon-mattermost-plain', color: '#7f7fab' },
  [ToolIcon.maven]: { name: 'Maven', icon: 'devicon-maven-plain', color: '#e97826' },
  [ToolIcon.maya]: { name: 'Maya', icon: 'devicon-maya-plain', color: '#149B9A' },
  [ToolIcon.memcached]: { name: 'Memcached', icon: 'devicon-memcached-plain', color: '#2A9790' },
  [ToolIcon.mercurial]: { name: 'Mercurial', icon: 'devicon-mercurial-plain', color: '#999' },
  [ToolIcon.meteor]: { name: 'Meteor', icon: 'devicon-meteor-plain', color: '#df5052' },
  [ToolIcon.microsoftsqlserver]: { name: 'SQL Server', icon: 'devicon-microsoftsqlserver-plain', color: '#ee352c' },
  [ToolIcon.minitab]: { name: 'Minitab', icon: 'devicon-minitab-plain', color: '#8dc63f' },
  [ToolIcon.mithril]: { name: 'Mithril.js', icon: 'devicon-mithril-plain', color: '#a954ff' },
  [ToolIcon.mobx]: { name: 'MobX', icon: 'devicon-mobx-plain', color: '#e05e11' },
  [ToolIcon.mocha]: { name: 'Mocha', icon: 'devicon-mocha-plain', color: '#b47440' },
  [ToolIcon.modx]: { name: 'MODX', icon: 'devicon-modx-plain', color: '#00decc' },
  [ToolIcon.moleculer]: { name: 'Moleculer', icon: 'devicon-moleculer-plain', color: '#3cafce' },
  [ToolIcon.mongodb]: { name: 'MongoDB', icon: 'devicon-mongodb-plain', color: '#4FAA41' },
  [ToolIcon.mongoose]: { name: 'Mongoose', icon: 'devicon-mongoose-original', color: '#ff0101' },
  [ToolIcon.monogame]: { name: 'MonoGame', icon: 'devicon-monogame-plain', color: '#f64000' },
  [ToolIcon.moodle]: { name: 'Moodle', icon: 'devicon-moodle-plain', color: '#F7931E' },
  [ToolIcon.msdos]: { name: 'MS-DOS', icon: 'devicon-msdos-plain', color: '#828282' },
  [ToolIcon.mysql]: { name: 'MySQL', icon: 'devicon-mysql-plain', color: '#008cc7' },
  [ToolIcon.nano]: { name: 'GNU Nano', icon: 'devicon-nano-plain', color: '#C8F' },
  [ToolIcon.nats]: { name: 'NATS', icon: 'devicon-nats-plain', color: '#27aae1' },
  [ToolIcon.neo4j]: { name: 'Neo4j', icon: 'devicon-neo4j-plain', color: '#018BFF' },
  [ToolIcon.neovim]: { name: 'Neovim', icon: 'devicon-neovim-plain', color: '#5fb950' },
  [ToolIcon.nestjs]: { name: 'NestJS', icon: 'devicon-nestjs-plain', color: '#e33e64' },
  [ToolIcon.netbeans]: { name: 'NetBeans', icon: 'devicon-netbeans-plain', color: '#2d81de' },
  [ToolIcon.netbox]: { name: 'NetBox', icon: 'devicon-netbox-plain', color: '#00948b' },
  [ToolIcon.netlify]: { name: 'Netlify', icon: 'devicon-netlify-plain', color: '#05BDBA' },
  [ToolIcon.networkx]: { name: 'NetworkX', icon: 'devicon-networkx-plain', color: '#2f88c4' },
  [ToolIcon.newrelic]: { name: 'New Relic', icon: 'devicon-newrelic-plain', color: '#5383ad' },
  [ToolIcon.nextjs]: { name: 'Next.js', icon: 'devicon-nextjs-plain', color: '#828282' },
  [ToolIcon.nginx]: { name: 'NGINX', icon: 'devicon-nginx-plain', color: '#090' },
  [ToolIcon.ngrok]: { name: 'ngrok', icon: 'devicon-ngrok-plain', color: '#4b74fc' },
  [ToolIcon.ngrx]: { name: 'NgRx', icon: 'devicon-ngrx-plain', color: '#c343d9' },
  [ToolIcon.nhibernate]: { name: 'NHibernate', icon: 'devicon-nhibernate-plain', color: '#c3635f' },
  [ToolIcon.nim]: { name: 'Nim', icon: 'devicon-nim-plain', color: '#ffe953' },
  [ToolIcon.nimble]: { name: 'Nimble', icon: 'devicon-nimble-plain', color: '#f7e941' },
  [ToolIcon.nixos]: { name: 'NixOS', icon: 'devicon-nixos-plain', color: '#5d80c7' },
  [ToolIcon.nodejs]: { name: 'Node.js', icon: 'devicon-nodejs-plain', color: '#5fa04e' },
  [ToolIcon.nodemon]: { name: 'Nodemon', icon: 'devicon-nodemon-plain', color: '#76d04b' },
  [ToolIcon.nodered]: { name: 'Node-RED', icon: 'devicon-nodered-plain', color: '#ff0a0a' },
  [ToolIcon.nodewebkit]: { name: 'NW.js', icon: 'devicon-nodewebkit-plain', color: '#847caf' },
  [ToolIcon.nomad]: { name: 'Nomad', icon: 'devicon-nomad-plain', color: '#00ca8e' },
  [ToolIcon.norg]: { name: 'Norg', icon: 'devicon-norg-plain', color: '#5380c2' },
  [ToolIcon.notion]: { name: 'Notion', icon: 'devicon-notion-plain', color: '#fff' },
  [ToolIcon.npm]: { name: 'npm', icon: 'devicon-npm-plain', color: '#d45c5b' },
  [ToolIcon.npss]: { name: 'NPSS', icon: 'devicon-npss-plain', color: '#517df5' },
  [ToolIcon.nuget]: { name: 'NuGet', icon: 'devicon-nuget-original', color: '#0084eb' },
  [ToolIcon.numpy]: { name: 'NumPy', icon: 'devicon-numpy-plain', color: '#4dabcf' },
  [ToolIcon.nuxt]: { name: 'Nuxt', icon: 'devicon-nuxt-plain', color: '#00dc82' },
  [ToolIcon.nuxtjs]: { name: 'Nuxt.js', icon: 'devicon-nuxtjs-plain', color: '#00c48d' },
  [ToolIcon.oauth]: { name: 'OAuth', icon: 'devicon-oauth-plain', color: '#828282' },
  [ToolIcon.objectivec]: { name: 'Objective-C', icon: 'devicon-objectivec-plain', color: '#1083e4' },
  [ToolIcon.ocaml]: { name: 'OCaml', icon: 'devicon-ocaml-plain', color: '#F18803' },
  [ToolIcon.ohmyzsh]: { name: 'Oh My Zsh', icon: 'devicon-ohmyzsh-plain', color: '#828282' },
  [ToolIcon.okta]: { name: 'Okta', icon: 'devicon-okta-plain', color: '#108cd0' },
  [ToolIcon.openal]: { name: 'OpenAL', icon: 'devicon-openal-plain', color: '#ff0922' },
  [ToolIcon.openapi]: { name: 'OpenAPI', icon: 'devicon-openapi-plain', color: '#91d400' },
  [ToolIcon.opencl]: { name: 'OpenCL', icon: 'devicon-opencl-plain', color: '#828282' },
  [ToolIcon.opencv]: { name: 'OpenCV', icon: 'devicon-opencv-plain', color: '#128dff' },
  [ToolIcon.opengl]: { name: 'OpenGL', icon: 'devicon-opengl-plain', color: '#5586a4' },
  [ToolIcon.openstack]: { name: 'OpenStack', icon: 'devicon-openstack-plain', color: '#ef355b' },
  [ToolIcon.opensuse]: { name: 'openSUSE', icon: 'devicon-opensuse-plain', color: '#73ba25' },
  [ToolIcon.opentelemetry]: { name: 'OpenTelemetry', icon: 'devicon-opentelemetry-plain', color: '#f5a800' },
  [ToolIcon.opera]: { name: 'Opera', icon: 'devicon-opera-plain', color: '#f7192d' },
  [ToolIcon.oracle]: { name: 'Oracle', icon: 'devicon-oracle-plain', color: '#ed373d' },
  [ToolIcon.ory]: { name: 'Ory', icon: 'devicon-ory-plain', color: '#8565ff' },
  [ToolIcon.p5js]: { name: 'p5.js', icon: 'devicon-p5js-plain', color: '#ee3067' },
  [ToolIcon.packer]: { name: 'Packer', icon: 'devicon-packer-plain', color: '#1d94dd' },
  [ToolIcon.pandas]: { name: 'pandas', icon: 'devicon-pandas-plain', color: '#816cf3' },
  [ToolIcon.passport]: { name: 'Passport.js', icon: 'devicon-passport-plain', color: '#35df79' },
  [ToolIcon.perl]: { name: 'Perl', icon: 'devicon-perl-plain', color: '#7676d9' },
  [ToolIcon.pfsense]: { name: 'pfSense', icon: 'devicon-pfsense-plain', color: '#828282' },
  [ToolIcon.phalcon]: { name: 'Phalcon', icon: 'devicon-phalcon-plain', color: '#76c39b' },
  [ToolIcon.phoenix]: { name: 'Phoenix', icon: 'devicon-phoenix-plain', color: '#FD4F00' },
  [ToolIcon.photonengine]: { name: 'Photon Engine', icon: 'devicon-photonengine-plain', color: '#007deb' },
  [ToolIcon.photoshop]: { name: 'Photoshop', icon: 'devicon-photoshop-plain', color: '#0084ee' },
  [ToolIcon.php]: { name: 'PHP', icon: 'devicon-php-plain', color: '#777bb3' },
  [ToolIcon.phpstorm]: { name: 'PhpStorm', icon: 'devicon-phpstorm-plain', color: '#b74af7' },
  [ToolIcon.pixijs]: { name: 'PixiJS', icon: 'devicon-pixijs-plain', color: '#ea3e77' },
  [ToolIcon.playwright]: { name: 'Playwright', icon: 'devicon-playwright-plain', color: '#2EAD33' },
  [ToolIcon.plotly]: { name: 'Plotly', icon: 'devicon-plotly-plain', color: '#6580c6' },
  [ToolIcon.pm2]: { name: 'PM2', icon: 'devicon-pm2-plain', color: '#828282' },
  [ToolIcon.pnpm]: { name: 'pnpm', icon: 'devicon-pnpm-plain', color: '#f9ad00' },
  [ToolIcon.podman]: { name: 'Podman', icon: 'devicon-podman-plain', color: '#b957d1' },
  [ToolIcon.poetry]: { name: 'Poetry', icon: 'devicon-poetry-plain', color: '#008ad4' },
  [ToolIcon.polygon]: { name: 'Polygon', icon: 'devicon-polygon-plain', color: '#8d6ae2' },
  [ToolIcon.portainer]: { name: 'Portainer', icon: 'devicon-portainer-plain', color: '#3BBCED' },
  [ToolIcon.postcss]: { name: 'PostCSS', icon: 'devicon-postcss-plain', color: '#ec3e0b' },
  [ToolIcon.postgresql]: { name: 'PostgreSQL', icon: 'devicon-postgresql-plain', color: '#4487bd' },
  [ToolIcon.postman]: { name: 'Postman', icon: 'devicon-postman-plain', color: '#f37036' },
  [ToolIcon.powershell]: { name: 'PowerShell', icon: 'devicon-powershell-plain', color: '#5080c0' },
  [ToolIcon.premierepro]: { name: 'Premiere Pro', icon: 'devicon-premierepro-plain', color: '#c645ea' },
  [ToolIcon.primeng]: { name: 'PrimeNG', icon: 'devicon-primeng-plain', color: '#828282' },
  [ToolIcon.prisma]: { name: 'Prisma', icon: 'devicon-prisma-plain', color: '#6484b9' },
  [ToolIcon.processing]: { name: 'Processing', icon: 'devicon-processing-plain', color: '#6275e3' },
  [ToolIcon.processwire]: { name: 'ProcessWire', icon: 'devicon-processwire-plain', color: '#1e87f0' },
  [ToolIcon.prolog]: { name: 'Prolog', icon: 'devicon-prolog-plain', color: '#F46C30' },
  [ToolIcon.prometheus]: { name: 'Prometheus', icon: 'devicon-prometheus-plain', color: '#e75225' },
  [ToolIcon.protractor]: { name: 'Protractor', icon: 'devicon-protractor-plain', color: '#e74758' },
  [ToolIcon.proxmox]: { name: 'Proxmox', icon: 'devicon-proxmox-plain', color: '#e57000' },
  [ToolIcon.pug]: { name: 'Pug', icon: 'devicon-pug-plain', color: '#c46a56' },
  [ToolIcon.pulsar]: { name: 'Pulsar', icon: 'devicon-pulsar-plain', color: '#4c83ba' },
  [ToolIcon.pulumi]: { name: 'Pulumi', icon: 'devicon-pulumi-plain', color: '#f6bf29' },
  [ToolIcon.puppeteer]: { name: 'Puppeteer', icon: 'devicon-puppeteer-plain', color: '#00d8a2' },
  [ToolIcon.purescript]: { name: 'PureScript', icon: 'devicon-purescript-original', color: '#697fab' },
  [ToolIcon.putty]: { name: 'PuTTY', icon: 'devicon-putty-plain', color: '#7777ff' },
  [ToolIcon.pycharm]: { name: 'PyCharm', icon: 'devicon-pycharm-plain', color: '#21D789' },
  [ToolIcon.pypi]: { name: 'PyPI', icon: 'devicon-pypi-plain', color: '#3f85c0' },
  [ToolIcon.pyscript]: { name: 'PyScript', icon: 'devicon-pyscript-plain-wordmark', color: '#fda703' },
  [ToolIcon.pytest]: { name: 'pytest', icon: 'devicon-pytest-plain', color: '#009fe3' },
  [ToolIcon.python]: { name: 'Python', icon: 'devicon-python-plain', color: '#ffd845' },
  [ToolIcon.pytorch]: { name: 'PyTorch', icon: 'devicon-pytorch-plain', color: '#EE4C2C' },
  [ToolIcon.qodana]: { name: 'Qodana', icon: 'devicon-qodana-plain', color: '#ff318c' },
  [ToolIcon.qt]: { name: 'Qt', icon: 'devicon-qt-plain', color: '#41cd52' },
  [ToolIcon.qtest]: { name: 'qTest', icon: 'devicon-qtest-plain', color: '#2a80e0' },
  [ToolIcon.quarkus]: { name: 'Quarkus', icon: 'devicon-quarkus-plain', color: '#4695EB' },
  [ToolIcon.quasar]: { name: 'Quasar', icon: 'devicon-quasar-plain', color: '#00b4ff' },
  [ToolIcon.qwik]: { name: 'Qwik', icon: 'devicon-qwik-plain', color: '#18B6F6' },
  [ToolIcon.r]: { name: 'R', icon: 'devicon-r-plain', color: '#3683dd' },
  [ToolIcon.rabbitmq]: { name: 'RabbitMQ', icon: 'devicon-rabbitmq-plain', color: '#ff6600' },
  [ToolIcon.racket]: { name: 'Racket', icon: 'devicon-racket-plain', color: '#de494d' },
  [ToolIcon.radstudio]: { name: 'RAD Studio', icon: 'devicon-radstudio-plain', color: '#f42434' },
  [ToolIcon.rails]: { name: 'Ruby on Rails', icon: 'devicon-rails-plain', color: '#ff0a0a' },
  [ToolIcon.railway]: { name: 'Railway', icon: 'devicon-railway-plain', color: '#fff' },
  [ToolIcon.rancher]: { name: 'Rancher', icon: 'devicon-rancher-plain', color: '#5277ff' },
  [ToolIcon.raspberrypi]: { name: 'Raspberry Pi', icon: 'devicon-raspberrypi-plain', color: '#e84277' },
  [ToolIcon.reach]: { name: 'Reach', icon: 'devicon-reach-plain', color: '#6AC6E7' },
  [ToolIcon.react]: { name: 'React', icon: 'devicon-react-plain', color: '#61dafb' },
  [ToolIcon.reactbootstrap]: { name: 'React Bootstrap', icon: 'devicon-reactbootstrap-plain', color: '#41e0fd' },
  [ToolIcon.reactnative]: { name: 'React Native', icon: 'devicon-reactnative-original', color: '#61dafb' },
  [ToolIcon.reactnavigation]: { name: 'React Navigation', icon: 'devicon-reactnavigation-plain', color: '#8d77ca' },
  [ToolIcon.reactrouter]: { name: 'React Router', icon: 'devicon-reactrouter-plain', color: '#f44250' },
  [ToolIcon.readthedocs]: { name: 'Read the Docs', icon: 'devicon-readthedocs-plain', color: '#858552' },
  [ToolIcon.realm]: { name: 'Realm', icon: 'devicon-realm-plain', color: '#7b6ffa' },
  [ToolIcon.rect]: { name: 'Rect', icon: 'devicon-rect-plain', color: '#828282' },
  [ToolIcon.redhat]: { name: 'Red Hat', icon: 'devicon-redhat-plain', color: '#ea424f' },
  [ToolIcon.redis]: { name: 'Redis', icon: 'devicon-redis-plain', color: '#e34d43' },
  [ToolIcon.redux]: { name: 'Redux', icon: 'devicon-redux-plain', color: '#8f6bc8' },
  [ToolIcon.reflex]: { name: 'Reflex', icon: 'devicon-reflex-plain', color: '#8471d1' },
  [ToolIcon.remix]: { name: 'Remix', icon: 'devicon-remix-plain', color: '#7d7d7d' },
  [ToolIcon.renpy]: { name: 'Ren\'Py', icon: 'devicon-renpy-plain', color: '#ff7f7f' },
  [ToolIcon.replit]: { name: 'Replit', icon: 'devicon-replit-plain', color: '#F26207' },
  [ToolIcon.rexx]: { name: 'REXX', icon: 'devicon-rexx-plain', color: '#ef3b37' },
  [ToolIcon.rider]: { name: 'Rider', icon: 'devicon-rider-plain', color: '#ee2f7d' },
  [ToolIcon.rocksdb]: { name: 'RocksDB', icon: 'devicon-rocksdb-plain', color: '#ffbe00' },
  [ToolIcon.rockylinux]: { name: 'Rocky Linux', icon: 'devicon-rockylinux-plain', color: '#10b982' },
  [ToolIcon.rollup]: { name: 'Rollup', icon: 'devicon-rollup-plain', color: '#ff3333' },
  [ToolIcon.ros]: { name: 'ROS', icon: 'devicon-ros-original', color: '#5d7db9' },
  [ToolIcon.rspec]: { name: 'RSpec', icon: 'devicon-rspec-plain', color: '#6de1fa' },
  [ToolIcon.rstudio]: { name: 'RStudio', icon: 'devicon-rstudio-plain', color: '#75aadb' },
  [ToolIcon.ruby]: { name: 'Ruby', icon: 'devicon-ruby-plain', color: '#fb2210' },
  [ToolIcon.rubymine]: { name: 'RubyMine', icon: 'devicon-rubymine-plain', color: '#FC801D' },
  [ToolIcon.rust]: { name: 'Rust', icon: 'devicon-rust-plain', color: '#828282' },
  [ToolIcon.rxjs]: { name: 'RxJS', icon: 'devicon-rxjs-plain', color: '#e63494' },
  [ToolIcon.safari]: { name: 'Safari', icon: 'devicon-safari-plain', color: '#1B88CA' },
  [ToolIcon.salesforce]: { name: 'Salesforce', icon: 'devicon-salesforce-plain', color: '#00a1e0' },
  [ToolIcon.sanity]: { name: 'Sanity', icon: 'devicon-sanity-plain', color: '#F03E2F' },
  [ToolIcon.sass]: { name: 'Sass', icon: 'devicon-sass-plain', color: '#cc6699' },
  [ToolIcon.scala]: { name: 'Scala', icon: 'devicon-scala-plain', color: '#e24d3e' },
  [ToolIcon.scalingo]: { name: 'Scalingo', icon: 'devicon-scalingo-plain', color: '#5e77f3' },
  [ToolIcon.scikitlearn]: { name: 'scikit-learn', icon: 'devicon-scikitlearn-plain', color: '#f89939' },
  [ToolIcon.sdl]: { name: 'SDL', icon: 'devicon-sdl-plain', color: '#4784cd' },
  [ToolIcon.selenium]: { name: 'Selenium', icon: 'devicon-selenium-plain', color: '#f42246' },
  [ToolIcon.sema]: { name: 'Sema', icon: 'devicon-sema-plain', color: '#828282' },
  [ToolIcon.sentry]: { name: 'Sentry', icon: 'devicon-sentry-plain', color: '#8471cd' },
  [ToolIcon.sequelize]: { name: 'Sequelize', icon: 'devicon-sequelize-plain', color: '#617fc6' },
  [ToolIcon.shopware]: { name: 'Shopware', icon: 'devicon-shopware-original', color: '#179eff' },
  [ToolIcon.shotgrid]: { name: 'ShotGrid', icon: 'devicon-shotgrid-plain', color: '#828282' },
  [ToolIcon.sketch]: { name: 'Sketch', icon: 'devicon-sketch-plain', color: '#fdad00' },
  [ToolIcon.slack]: { name: 'Slack', icon: 'devicon-slack-plain', color: '#6785a9' },
  [ToolIcon.socketio]: { name: 'Socket.IO', icon: 'devicon-socketio-plain', color: '#838383' },
  [ToolIcon.solidity]: { name: 'Solidity', icon: 'devicon-solidity-plain', color: '#7d7d7d' },
  [ToolIcon.solidjs]: { name: 'SolidJS', icon: 'devicon-solidjs-plain', color: '#5283c1' },
  [ToolIcon.sonarqube]: { name: 'SonarQube', icon: 'devicon-sonarqube-plain', color: '#549dd0' },
  [ToolIcon.sourceengine]: { name: 'Source Engine', icon: 'devicon-sourceengine-plain', color: '#f79a10' },
  [ToolIcon.sourcetree]: { name: 'Sourcetree', icon: 'devicon-sourcetree-plain', color: '#3d85cf' },
  [ToolIcon.spack]: { name: 'Spack', icon: 'devicon-spack-plain', color: '#3f80e9' },
  [ToolIcon.spicedb]: { name: 'SpiceDB', icon: 'devicon-spicedb-plain', color: '#FB5B62' },
  [ToolIcon.splunk]: { name: 'Splunk', icon: 'devicon-splunk-original-wordmark', color: '#5186c5' },
  [ToolIcon.spring]: { name: 'Spring', icon: 'devicon-spring-plain', color: '#5FB832' },
  [ToolIcon.spss]: { name: 'SPSS', icon: 'devicon-spss-plain', color: '#e3446e' },
  [ToolIcon.spyder]: { name: 'Spyder', icon: 'devicon-spyder-plain', color: '#ff0707' },
  [ToolIcon.sqlalchemy]: { name: 'SQLAlchemy', icon: 'devicon-sqlalchemy-plain', color: '#808080' },
  [ToolIcon.sqldeveloper]: { name: 'SQL Developer', icon: 'devicon-sqldeveloper-plain', color: '#adadad' },
  [ToolIcon.sqlite]: { name: 'SQLite', icon: 'devicon-sqlite-plain', color: '#1089da' },
  [ToolIcon.ssh]: { name: 'SSH', icon: 'devicon-ssh-plain', color: '#a47480' },
  [ToolIcon.stackblitz]: { name: 'StackBlitz', icon: 'devicon-stackblitz-plain', color: '#1389fd' },
  [ToolIcon.stackoverflow]: { name: 'Stack Overflow', icon: 'devicon-stackoverflow-plain', color: '#F58025' },
  [ToolIcon.stata]: { name: 'Stata', icon: 'devicon-stata-original-wordmark', color: '#248ad3' },
  [ToolIcon.stenciljs]: { name: 'Stencil', icon: 'devicon-stenciljs-plain', color: '#828282' },
  [ToolIcon.storybook]: { name: 'Storybook', icon: 'devicon-storybook-plain', color: '#FF4785' },
  [ToolIcon.streamlit]: { name: 'Streamlit', icon: 'devicon-streamlit-plain', color: '#c16c73' },
  [ToolIcon.styledcomponents]: { name: 'styled-components', icon: 'devicon-styledcomponents-plain', color: '#d268a7' },
  [ToolIcon.stylus]: { name: 'Stylus', icon: 'devicon-stylus-original', color: '#808080' },
  [ToolIcon.subversion]: { name: 'Subversion', icon: 'devicon-subversion-plain', color: '#809cc8' },
  [ToolIcon.sulu]: { name: 'Sulu', icon: 'devicon-sulu-plain', color: '#3e83d0' },
  [ToolIcon.supabase]: { name: 'Supabase', icon: 'devicon-supabase-plain', color: '#3ecf8e' },
  [ToolIcon.surrealdb]: { name: 'SurrealDB', icon: 'devicon-surrealdb-plain', color: '#e600f0' },
  [ToolIcon.svelte]: { name: 'Svelte', icon: 'devicon-svelte-plain', color: '#ff3e00' },
  [ToolIcon.svgo]: { name: 'SVGO', icon: 'devicon-svgo-plain', color: '#fff' },
  [ToolIcon.swagger]: { name: 'Swagger', icon: 'devicon-swagger-plain', color: '#85ea2d' },
  [ToolIcon.swift]: { name: 'Swift', icon: 'devicon-swift-plain', color: '#F05138' },
  [ToolIcon.swiper]: { name: 'Swiper', icon: 'devicon-swiper-plain', color: '#0080FF' },
  [ToolIcon.symfony]: { name: 'Symfony', icon: 'devicon-symfony-plain', color: '#9971a6' },
  [ToolIcon.tailwindcss]: { name: 'Tailwind CSS', icon: 'devicon-tailwindcss-plain', color: '#38bdf8' },
  [ToolIcon.talos]: { name: 'Talos', icon: 'devicon-talos-plain', color: '#f92a20' },
  [ToolIcon.tauri]: { name: 'Tauri', icon: 'devicon-tauri-plain', color: '#FFC131' },
  [ToolIcon.teleport]: { name: 'Teleport', icon: 'devicon-teleport-plain', color: '#8c75df' },
  [ToolIcon.tensorflow]: { name: 'TensorFlow', icon: 'devicon-tensorflow-original', color: '#ff6f00' },
  [ToolIcon.terraform]: { name: 'Terraform', icon: 'devicon-terraform-plain', color: '#8176eb' },
  [ToolIcon.terramate]: { name: 'Terramate', icon: 'devicon-terramate-plain', color: '#fff' },
  [ToolIcon.tex]: { name: 'TeX', icon: 'devicon-tex-plain', color: '#828282' },
  [ToolIcon.thealgorithms]: { name: 'The Algorithms', icon: 'devicon-thealgorithms-plain', color: '#00BCB4' },
  [ToolIcon.threedsmax]: { name: '3ds Max', icon: 'devicon-threedsmax-plain', color: '#37a5cc' },
  [ToolIcon.threejs]: { name: 'Three.js', icon: 'devicon-threejs-original', color: '#828282' },
  [ToolIcon.thymeleaf]: { name: 'Thymeleaf', icon: 'devicon-thymeleaf-plain', color: '#009c19' },
  [ToolIcon.titaniumsdk]: { name: 'Titanium SDK', icon: 'devicon-titaniumsdk-plain', color: '#df4d55' },
  [ToolIcon.tmux]: { name: 'tmux', icon: 'devicon-tmux-plain', color: '#1bb91f' },
  [ToolIcon.tomcat]: { name: 'Tomcat', icon: 'devicon-tomcat-line', color: '#D1A41A' },
  [ToolIcon.tortoisegit]: { name: 'TortoiseGit', icon: 'devicon-tortoisegit-plain', color: '#4b8eb4' },
  [ToolIcon.towergit]: { name: 'Tower', icon: 'devicon-towergit-plain', color: '#d18900' },
  [ToolIcon.traefikmesh]: { name: 'Traefik Mesh', icon: 'devicon-traefikmesh-plain', color: '#d420ec' },
  [ToolIcon.traefikproxy]: { name: 'Traefik', icon: 'devicon-traefikproxy-plain', color: '#24a1c1' },
  [ToolIcon.travis]: { name: 'Travis CI', icon: 'devicon-travis-plain', color: '#6882a3' },
  [ToolIcon.trello]: { name: 'Trello', icon: 'devicon-trello-plain', color: '#297fff' },
  [ToolIcon.trpc]: { name: 'tRPC', icon: 'devicon-trpc-plain', color: '#398ccb' },
  [ToolIcon.turbo]: { name: 'Turborepo', icon: 'devicon-turbo-plain', color: '#5cd8e5' },
  [ToolIcon.twilio]: { name: 'Twilio', icon: 'devicon-twilio-plain', color: '#f22f46' },
  [ToolIcon.twitter]: { name: 'Twitter', icon: 'devicon-twitter-plain', color: '#828282' },
  [ToolIcon.typescript]: { name: 'TypeScript', icon: 'devicon-typescript-plain', color: '#0083db' },
  [ToolIcon.typo3]: { name: 'TYPO3', icon: 'devicon-typo3-plain', color: '#f49700' },
  [ToolIcon.ubuntu]: { name: 'Ubuntu', icon: 'devicon-ubuntu-plain', color: '#e95420' },
  [ToolIcon.unifiedmodelinglanguage]: { name: 'UML', icon: 'devicon-unifiedmodelinglanguage-plain', color: '#9078ce' },
  [ToolIcon.unity]: { name: 'Unity', icon: 'devicon-unity-plain', color: '#838383' },
  [ToolIcon.unix]: { name: 'UNIX', icon: 'devicon-unix-original', color: '#7481ce' },
  [ToolIcon.unrealengine]: { name: 'Unreal Engine', icon: 'devicon-unrealengine-plain', color: '#828282' },
  [ToolIcon.uwsgi]: { name: 'uWSGI', icon: 'devicon-uwsgi-plain', color: '#bad05e' },
  [ToolIcon.v8]: { name: 'V8', icon: 'devicon-v8-plain', color: '#00C4CC' },
  [ToolIcon.vaadin]: { name: 'Vaadin', icon: 'devicon-vaadin-plain', color: '#00b4f0' },
  [ToolIcon.vagrant]: { name: 'Vagrant', icon: 'devicon-vagrant-plain', color: '#127eff' },
  [ToolIcon.vala]: { name: 'Vala', icon: 'devicon-vala-plain', color: '#a56de2' },
  [ToolIcon.vault]: { name: 'Vault', icon: 'devicon-vault-plain', color: '#ffd814' },
  [ToolIcon.veevalidate]: { name: 'VeeValidate', icon: 'devicon-veevalidate-plain', color: '#04c971' },
  [ToolIcon.vercel]: { name: 'Vercel', icon: 'devicon-vercel-plain', color: '#828282' },
  [ToolIcon.vertx]: { name: 'Vert.x', icon: 'devicon-vertx-plain', color: '#b258cf' },
  [ToolIcon.vim]: { name: 'Vim', icon: 'devicon-vim-plain', color: '#179a33' },
  [ToolIcon.visualbasic]: { name: 'Visual Basic', icon: 'devicon-visualbasic-plain', color: '#0081e8' },
  [ToolIcon.visualstudio]: { name: 'Visual Studio', icon: 'devicon-visualstudio-plain', color: '#9e69db' },
  [ToolIcon.vite]: { name: 'Vite', icon: 'devicon-vite-plain', color: '#1f7dff' },
  [ToolIcon.vitejs]: { name: 'Vite', icon: 'devicon-vitejs-plain', color: '#ffdd35' },
  [ToolIcon.vitess]: { name: 'Vitess', icon: 'devicon-vitess-plain', color: '#f16827' },
  [ToolIcon.vitest]: { name: 'Vitest', icon: 'devicon-vitest-plain', color: '#fcc72b' },
  [ToolIcon.vscode]: { name: 'VS Code', icon: 'devicon-vscode-plain', color: '#3C99D4' },
  [ToolIcon.vscodium]: { name: 'VSCodium', icon: 'devicon-vscodium-plain', color: '#3C99D4' },
  [ToolIcon.vsphere]: { name: 'vSphere', icon: 'devicon-vsphere-plain', color: '#0091da' },
  [ToolIcon.vuejs]: { name: 'Vue.js', icon: 'devicon-vuejs-plain', color: '#41B883' },
  [ToolIcon.vuestorefront]: { name: 'Vue Storefront', icon: 'devicon-vuestorefront-plain', color: '#5ecf7b' },
  [ToolIcon.vuetify]: { name: 'Vuetify', icon: 'devicon-vuetify-plain', color: '#1697F6' },
  [ToolIcon.vulkan]: { name: 'Vulkan', icon: 'devicon-vulkan-plain', color: '#e7465d' },
  [ToolIcon.vyper]: { name: 'Vyper', icon: 'devicon-vyper-plain', color: '#a75af3' },
  [ToolIcon.waku]: { name: 'Waku', icon: 'devicon-waku-plain', color: '#e1485c' },
  [ToolIcon.wasm]: { name: 'WebAssembly', icon: 'devicon-wasm-plain', color: '#7e6bf2' },
  [ToolIcon.web3js]: { name: 'Web3.js', icon: 'devicon-web3js-plain', color: '#f16822' },
  [ToolIcon.webflow]: { name: 'Webflow', icon: 'devicon-webflow-original', color: '#626fff' },
  [ToolIcon.webgpu]: { name: 'WebGPU', icon: 'devicon-webgpu-plain', color: '#0086e9' },
  [ToolIcon.weblate]: { name: 'Weblate', icon: 'devicon-weblate-plain', color: '#2eccaa' },
  [ToolIcon.webpack]: { name: 'webpack', icon: 'devicon-webpack-plain', color: '#2089db' },
  [ToolIcon.webstorm]: { name: 'WebStorm', icon: 'devicon-webstorm-plain', color: '#07c3f2' },
  [ToolIcon.windows11]: { name: 'Windows 11', icon: 'devicon-windows11-plain', color: '#0081e3' },
  [ToolIcon.windows8]: { name: 'Windows 8', icon: 'devicon-windows8-plain', color: '#00adef' },
  [ToolIcon.wolfram]: { name: 'Wolfram', icon: 'devicon-wolfram-plain', color: '#fc1300' },
  [ToolIcon.woocommerce]: { name: 'WooCommerce', icon: 'devicon-woocommerce-plain', color: '#9774c1' },
  [ToolIcon.wordpress]: { name: 'WordPress', icon: 'devicon-wordpress-plain', color: '#7f7f7f' },
  [ToolIcon.xamarin]: { name: 'Xamarin', icon: 'devicon-xamarin-plain', color: '#3498DB' },
  [ToolIcon.xcode]: { name: 'Xcode', icon: 'devicon-xcode-plain', color: '#069CEC' },
  [ToolIcon.xd]: { name: 'Adobe XD', icon: 'devicon-xd-plain', color: '#ed03b8' },
  [ToolIcon.xml]: { name: 'XML', icon: 'devicon-xml-plain', color: '#0081ea' },
  [ToolIcon.yaml]: { name: 'YAML', icon: 'devicon-yaml-plain', color: '#ea454b' },
  [ToolIcon.yarn]: { name: 'Yarn', icon: 'devicon-yarn-plain', color: '#2c8ebb' },
  [ToolIcon.yii]: { name: 'Yii', icon: 'devicon-yii-plain', color: '#40b3d8' },
  [ToolIcon.yugabytedb]: { name: 'YugabyteDB', icon: 'devicon-yugabytedb-plain', color: '#ff5f3b' },
  [ToolIcon.yunohost]: { name: 'YunoHost', icon: 'devicon-yunohost-plain', color: '#ffffff' },
  [ToolIcon.zend]: { name: 'Zend', icon: 'devicon-zend-plain', color: '#68b604' },
  [ToolIcon.zig]: { name: 'Zig', icon: 'devicon-zig-plain', color: '#f7a41d' },
  [ToolIcon.zsh]: { name: 'Zsh', icon: 'devicon-zsh-plain', color: '#828282' },
  [ToolIcon.zustand]: { name: 'Zustand', icon: 'devicon-zustand-plain', color: '#9a7b5d' },
};