services:
  webserver:
    container_name: Webserver
    image: mcmodersd/mcmodersd.de:angular-latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - "80:4000/tcp"

networks:
  default:
    name: Webserver-Network