HTTP/1.1 403 Forbidden
Content-Type: text/html

<html lang="en">
<head>
    <title>403 Forbidden</title>
</head>
<body
        style=
                "
                color: #72b1f4;
                background-color: #0a0c10;
                margin-top: 12.5%;
                font-size: 4rem;
                font-family: sans-serif;
                text-align: center;">

<h1>403 Forbidden</h1>
<p>You don't have permission to access this resource.</p>

</body>
</html>
