HTTP/1.1 404 Not Found
Content-Type: text/html

<html lang="en">
<head>
    <title>404 Not Found</title>
</head>
<body
        style=
                "
                color: #72b1f4;
                background-color: #0a0c10;
                margin-top: 12.5%;
                font-size: 4rem;
                font-family: sans-serif;
                text-align: center;">

<h1>404 Not Found</h1>
<p>The requested URL was not found on this server.</p>

</body>
</html>