HTTP/1.1 503 Service Unavailable
Content-Type: text/html

<html lang="en">
<head>
    <title>503 Service Unavailable</title>
</head>
<body
        style=
                "
                color: #72b1f4;
                background-color: #0a0c10;
                margin-top: 12.5%;
                font-size: 4rem;
                font-family: sans-serif;
                text-align: center;">

    <h1>503 Service Unavailable</h1>
    <p>The server is currently unable to handle the request.</p>

</body>
</html>