HTTP/1.1 X1
Content-Type: text/html

<html lang="en">
<head>
    <title>X1</title>
</head>
<body
        style=
                "
                color: #72b1f4;
                background-color: #0a0c10;
                margin-top: 12.5%;
                font-size: 4rem;
                font-family: sans-serif;
                text-align: center;">

<h1>X1</h1>
<p>X2</p>

</body>
</html>